### ISSUE TITLE
Frontend issues

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaodjin-saas#112]
1. "Roles" link in the header navigation is broken
2. "Unsubscribe Now" button is broken [here](http://localhost:8000/profile/demo86/subscriptions/)
3. [Here](http://localhost:8000/profile/cowork-master/subscribers/) "Registered" table seems to be broken (no data)
3. [Here](http://localhost:8000/profile/cowork-master/subscribers/) "Churned" and "Registered" table filters are filtering the "Active" table, instead of the respective ones

**Comment by smirolo** [comment]
1. "Roles" link fixed at commit cb633444
2. "Unsubscribed Now" fixed at commit 22017221 and commit cb633444
3. "Registered" table loaded at commit cb633444
4. "Churned" and "Registered" tables filtered at commit db26c598
