### ISSUE TITLE
returns 3-letter unit code in metrics APIs

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaodjin-saas#123]
In [balance API](https://github.com/djaodjin/djaodjin-saas/blob/5538bd171037a070252c845f83c7d00c1a576a09/saas/api/metrics.py#L128) and [revenue API](https://github.com/djaodjin/djaodjin-saas/blob/5538bd171037a070252c845f83c7d00c1a576a09/saas/api/metrics.py#L266), the unit is hardcoded to '$'.

1. The unit should be the 3-letter unit code (ex: usd)
2. The unit should be derived from the Transaction aggregated.

**Comment by knivets** [comment]
Should I modify `monthly_balances` to return unit code besides amount and period?

**Comment by smirolo** [comment]
Yes. It seems like the obvious choice. `sum_dest_amount` and `sum_orig_amount` already have a similar prototype.
