### ISSUE TITLE
Checkout group_by problem

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaodjin-saas#155]
Adding a plan, selecting an option, doing a csv import (with 3 accounts), which replaces the first line with first account and adds two more accounts, resulting in total 3 lines. Then if I click on add button (which adds a single account) but leave the inputs empty it will delete the last line and it will show a list of options. When selecting an option we are redirected to payment page and not to /cart-seats page.

**Comment by smirolo** [comment]
released as part of version 0.11.0
