### ISSUE TITLE
Error response received from Stripe during test payments

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#16]
Using a test card and submitting a payment leads to this warning banner being displayed across the top of the reloaded credit card form page: 

  Received unknown parameter: statement_description

The development server console shows the following:

  127.0.0.1 cowork_user9 ERROR [03/Apr/2015:11:04:21 +0000] InvalidRequestError for charge of 17999 cents to cowork_user9

This message originates from the Stripe API, which is responding to our API submission of the payment with the following:

```
error:
type: "invalid_request_error"
message: "Received unknown parameter: statement_description"
param: "statement_description"
```

See: https://github.com/djaodjin/djaodjin-saas/blob/935e6cdc79365eadb9544341c40b80efa1c0cfc0/saas/models.py#L554

**Comment by smirolo** [comment]
On stripe.com, the accounts settings displays we are using

    API Version: 2014-03-28

**Comment by marmida** [comment]
This also works with API version `2012-07-09`.
