### ISSUE TITLE
Account signup asks for captcha when there is none

### ISSUE THREAD

**Issue by jpoechill** [djaodjin/djaodjin-saas#202]
Issue: Signing up for an account is not able to complete because form asks for captcha when there is none.

Steps to reproduce: Complete sign up form, filling all available fields. Click 'Sign Up'.

Expected: User should be able to successfully create a new account.

What is happening: Error message shows, 'These input fields are missing: captcha.'.

--

Link for reference: https://djaodjin.com/register/

**Comment by smirolo** [comment]
Fix deployed. Thanks Po!
