### ISSUE TITLE
Add coupon code to receipt email

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#21]
Currently, the email receipt sent to the provider / admin includes the coupon percentage, but not the code, for each registration. Add the code to this email.

**Comment by marmida** [comment]
This receipt email isn't triggered during registration on the test site. This is because the test site isn't configured to send that particular email. In previous demos, we've triggered it through the Djaodjin production site, which does invoke that feature.

The core alerts the wrapper site via a signal. This is handled by `djaodjin/signals.py`. The receipt is generated by `djaodjin/djaodjin/templates/saas/charge_receipt.eml`.

**Comment by marmida** [comment]
Currently the relevant receiver for the `order_updated` signal is the `order_executed_notice` function in the `djaodjin/djaodjin/signals.py` module. At the point at which this invoked, we've discarded the necessary info from the original Stripe transaction to be able to present the coupon info; we are given a series of `Transaction` model objects, each representing a line item, and the price of this has already been modified to reflect the coupon application.

Off the top of my head, we could:

1. add more line items with negative values, which would represent the coupon's discount
1. add fields to the transaction to save the coupon info
1. try to get more info from earlier on - like maybe the original Stripe transaction response object - passed through the signal.

@smirolo what do you think?

**Comment by marmida** [comment]
My steps to reproduce this:

1. edit `djaodjin/djaodjin/signals.py` and add a `pdb.set_trace()` call to `order_executed_notice`
1. run the `djaodjin/manage.py` development server
1. register a user using the `DIS50` coupon

**Comment by smirolo** [comment]
ok... what we have done so far is to append a (discount) description in  the method `create_order` in models.py:

    descr += ' - a %d%% discount' % discount_percent

The Coupon code should surely be added at that point in the description.

1. "add more line items" will change the balance sheet. My preferred method if we start to track potential revenue vs. actual revenue. This is more of an accounting decision. It will have a wide impact on data already stored in production dbs as well as various reports generated.

2. "add fields to the transaction". I don't like this one much. Better keep the `Transaction` table as clean as possible, with the minimum information for running a double-entry ledger. Pricing/Coupons should stay tied to a customer cart (i.e. `CartItem` table).

3. "try to get more info from earlier on". That is essentially what the append to description method above does. I would prefer to keep Stripe stuff into its own `backend` if possible.

**Comment by marmida** [comment]
We've merged an implementation on this, although there is ongoing discussion about exactly how it should be done.
