### ISSUE TITLE
Add "delete" for plans

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#22]
Add a "delete" button to plans that have no subscribers.

This applies to plans that have never had any subscribers. Plans that have had at least one subscriber cannot be deleted; they can only be deactivated. Peleted plans are physically removed from the database.

**Comment by marmida** [comment]
I think the place to put this is as a button next to the "Update" and "Activate" buttons on the "Update Plan" page. This is a Django update form view handling updates to a single model.

The "Activate" button is different, because it uses JavaScript to send a HTTP PATCH request to change the Plan's activation status. This then doesn't move the user's browser or add any other message to the page to indicate that the request has been completed; the button simply changes from "Activate" to "Deactivate".

In the case of deleting the plan altogether, I think it's more appropriate to use a regular Django view. This is because:

1. we want the browser to move to another location after the action is completed; we'll show the main Plan metrics screen again
1. we want to add a message flash across the top of the screen, saying "Plan XXX deleted." This is easiest to do in a Django view, and there is some precedent in the Update Plan form, which already does this.
1. we want to redirect after post to prevent the user from attempting to re-delete the same plan with a refresh.

Does this sound okay to you, @smirolo ?

**Comment by smirolo** [comment]
Sounds terrific! Django View it is. Thanks.
