### ISSUE TITLE
Easy docker setup

### ISSUE THREAD

**Issue by YPCrumble** [djaodjin/djaodjin-saas#232]
Thanks for building this!

It would be awesome to have a docker container that one could quickly setup and deploy to any cloud host with minimal effort. Currently I don't see documentation on deployment and having a super fast way to deploy would make this incredibly useful!

**Comment by smirolo** [comment]
Read my mind. With GitHub supporting packages, it is definitely something we are working on sooner rather than later.

**Comment by smirolo** [comment]
Sorry I forgot to write an update here. Though we might not create Docker container for this project per-se, there is one in [djaoapp](https://github.com/djaodjin/djaoapp), a project that integrates this Django app with various others, bootstrap4 templates and French/Spanish/Portuguese translations.

I recommend you try the [livedemo Docker container](https://github.com/djaodjin/djaoapp/packages/270509). It is populated with mockup data, also live at https://livedemo.djaoapp.com/.
If you like it, you can deploy the [djaoapp Docker container](https://github.com/djaodjin/djaoapp/packages/270494) which is suitable for production.
