### ISSUE TITLE
Export financial transactions as CSV

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#24]
Two admin views show financial transactions: "funds" and "billing." In both cases, we want to add both (1) the same style of date picker as on the "Retention" screen, allowing for filtering the transactions by date, and (2) a CSV download of the transaction data.

TODO: specify the CSV fields in each case.

**Comment by smirolo** [comment]
Fields:
- created_at
- descr
- orig_amount / orig_unit or dest_amount / dest_unit depending on both orig_account and dest_account.

In the double entry ledger which the Transaction table is, which side (orig/dest) is printed depends on the point or reference. On the funds page we are interested into producing what goes in / out of the provider. On the billing page we are interested into what goes in / out of the subscriber.

**Comment by marmida** [comment]
Check out `TransactionListBaseAPIView` in `transactions.py` for this.

**Comment by marmida** [comment]
The export should always use the `dest_amount` field, in both cases. The difference between the fields is primarily about units - for each ledger entry (a row), the amounts are always the same, unless they are in different currencies. In both cases, we want the download to include the amount and units relative to the receiver, hence the preference for the `dest_` fields.

It would be helpful if we included minus signs ahead of debit amounts; beware that all entries in the transactions table will be positive. This logic is in `TransactionSerializer._is_debit` and the `is_debit` template tag.

**Comment by smirolo** [comment]
Transactions in CSV should be sorted by date. Right now, the order just looks random.

**Comment by marmida** [comment]
You're probably right - I don't think I specified a sort order, so they're going to be randomly ordered by the database. I'll fix it.

**Comment by smirolo** [comment]
done.
