### ISSUE TITLE
Move revenue / financials view backwards and forwards in time

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#29]
Allow the user viewing the financial revenue graph in the provider admin the ability to move that view forward or back in time. Because the number of months determines the width of the page, it may be best to only allow them to slide the start and end dates, together, forward by N months, instead of allowing them to choose an arbitrary start and end date (and thus, require more horizontal space on the page).

**Comment by smirolo** [comment]
Perfect. a fixed 12-month trailing view from a sliding date makes the most sense. It should be possible to go forward in the future though (for predictive cash flow analysis).

**Comment by marmida** [comment]
Some more investigation / discussion:

1. the current page can change its date range simply by adding the `ends_at` query parameter in the format `YYYY-MM-DD HH:MM:SS` (urlencoded), e.g. `/provider/metrics/?ends_at=2015-01-01+10%3A10%3A10`.
1. we don't want to refresh the entire page, however
1. move the data from inline markup generated by Django to an API endpoint
1. change D3 to pull from a JS array instead
1. build the array via Angular after making API calls

**Comment by marmida** [comment]
Ignoring the desire to expand this feature to the "Plans" page, is there anything left to do on this issue? I think we're ready to close this, yeah, @smirolo ?

**Comment by smirolo** [comment]
agreed. closed. Thank you!
