### ISSUE TITLE
Cannot register with non-ASCII content in form

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#34]
Validation rules fire that prevent the entry of non-ASCII content into the registration form. See the attached image.

![unicode_reg](https://cloud.githubusercontent.com/assets/420896/7303821/fc772602-e9a7-11e4-863b-8bd6a19122a5.png)

This may be specific to the wrapping site, or may be part of the `djaodjin-saas` core. I'm not certain. It should be the case that the registration form instead allows non-ASCII input.

**Comment by smirolo** [comment]
Migrated to a [djaodjin-signup issue](https://github.com/djaodjin/djaodjin-signup/issues/7).
