### ISSUE TITLE
"Balances" download view produces a bad CSV

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#36]
Here's the file generated by the "balances" screen from an export of bogus data in the `djaodjin` test site: 
https://gist.github.com/marmida/1d4b94ab3da3d634cb0a

This contains several rows of data on the same line, and has no heading. We should probably add a heading and break data across lines - otherwise this isn't a CSV!

**Comment by smirolo** [comment]
See commit 88feb47c9bed33b3d04f1f587a4341bc1a07ccb2
