### ISSUE TITLE
Invalid routing number triggers cryptic validation complaint: "Routing Number field(s) cannot be empty."

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#40]
Trying to start a withdrawal with an invalid bank account number causes the following error message to be displayed to the user: `Routing Number field(s) cannot be empty.`

![routing_validation](https://cloud.githubusercontent.com/assets/420896/7421987/f558a486-ef3d-11e4-98bd-729ea15c3e70.png)

This is counter-intuitive, because the user did provide a routing number (it's just invalid, and Stripes' JS library has rejected it -- unfortunately, that function does nothing more than indicate validation success, without any explanantion. See: https://stripe.com/docs/stripe.js?#bank-account-validateRoutingNumber)

**Comment by smirolo** [comment]
This issue is now irrelevant since Stripe deprecated the ``Recipient`` feature. Rely on StripeConnect instead in [version 0.2.0](https://github.com/djaodjin/djaodjin-saas/tree/0.2.0).
