### ISSUE TITLE
I want to add different apps to a Particular Plan.

### ISSUE THREAD

**Issue by vaibhav-jain** [djaodjin/djaodjin-saas#84]
I want to know how to implement Plan with features like [Freshdesk](https://freshdesk.com/pricing) do.
 Like they can enable or disable features within a Particular Plan

**Comment by smirolo** [comment]
In decorators.py there is a ``requires_paid_subscription`` [decorator](https://github.com/djaodjin/djaodjin-saas/blob/master/saas/decorators.py#L405) which is part of the [flexible security framework](http://djaodjin-saas.readthedocs.org/en/latest/security.html#saas.decorators.requires_paid_subscription).

What you would do to allow/deny access to certain features (i.e. URLs) based on the subscribed-to ``Plan`` is to decorate the view implementing the feature.

Example:
     urls.py:

     from saas.decorators import requires_paid_subscription
     from .views import FeatureView

    urlpatterns = [
    ...
    url(r'^(?P<organization>[a-z])/(?P<subscribed_plan>[a-z])/feature/',
        requires_paid_subscription(FeatureView.as_view()), name='feature'),
    ...
    ]

It is pretty straightforward to create new sets of decorators such that the ``Plan`` does not have to be part of the URL. Let me know if that would be helpful. Maybe something like:

    def requires_paid_subscription(function=None,
        organization_kwarg_slug='organization',
        plans=None):      # plans is a list of ``Plan`` organization must be subscribed to.

**Comment by vaibhav-jain** [comment]
@smirolo thanks for your reply. I think this we will help us.
